PETSAFE_API_BASE = "https://platform.cloud.petsafe.net/"
PETSAFE_CLIENT_ID = "18hpp04puqmgf5nc6o474lcp2g"
PETSAFE_REGION = "us-east-1"

FOOD_LEVEL_FULL = 0
FOOD_LEVEL_LOW = 1
FOOD_LEVEL_EMPTY = 2
SMARTDOOR_MODE_MANUAL_LOCKED = "MANUAL_LOCKED"
SMARTDOOR_MODE_MANUAL_UNLOCKED = "MANUAL_UNLOCKED"
SMARTDOOR_MODE_SMART = "SMART"
SMARTDOOR_FINAL_ACT_LOCKED = "LOCKED"
SMARTDOOR_FINAL_ACT_UNLOCKED = "UNLOCKED"
